services:
  web:
    build:
      context: .
      dockerfile: php.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - ./app:/var/www/html
    environment:
      - DOMAIN=http://localhost
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=mydb
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
  db:
    image: postgres:alpine3.20
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
volumes:
  db-data: